name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # State Management
  mobx:
  flutter_mobx:
  mobx_codegen:
  # Local Database
  moor_flutter:
  moor_generator:
  # For the required annotation
  meta:
  # Service Locator
  get_it: ^3.1.0
  # http client
  dio: ^3.0.8
  # Json serializer helper
  json_serializable:
  json_annotation: ^3.0.1
  #  i18n
  intl:
  # Pull to refresh
  pull_to_refresh: ^1.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:

  uses-material-design: true